version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: beyoureyes
      POSTGRES_PASSWORD: secure_password_2025
      POSTGRES_DB: be_your_eyes_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U beyoureyes"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./be_your_eyes_backend
    environment:
      DATABASE_URL: postgresql://beyoureyes:secure_password_2025@db:5432/be_your_eyes_db
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

volumes:
  postgres_data: