from .direccion import Direccion
from .tipo_local import TipoLocal
from .local import Local
from .menu import Menu
from .categoria import Categoria
from .menu_categoria import MenuCategoria
from .plato import Plato
from .punto_impresion import PuntoImpresion
from .usuario import Usuario
from .persona import Persona
from .local import Local
from .horario import Horario
from .notificacion import Notificacion